version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@material/fab"
    versions:
    - "> 3.2.0"
  - dependency-name: "@material/snackbar"
    versions:
    - "> 3.2.0"
  - dependency-name: "@material/dom"
    versions:
    - "> 3.2.0"
  - dependency-name: "@material/icon-button"
    versions:
    - "> 3.2.0"
  - dependency-name: "@material/react-linear-progress"
    versions:
    - "> 0.15.0"
  - dependency-name: "@material/ripple"
    versions:
    - "> 3.2.0"
