git:
  tagName: 'v${version}'
  tagAnnotation: 'Release v${version}'
  commitMessage: 'Release v${version}'
  pushArgs: ['--follow-tags', '--force']
npm:
  publish: false
plugins:
  @release-it/keep-a-changelog:
    filename: 'CHANGELOG.md'
