const commonColors = {
  'green-1': 'var(--green-1)',
  'red-1': 'var(--red-1)',
  'violet-1': 'var(--violet-1)',
  'violet-2': 'var(--violet-2)',
  'yellow-1': 'var(--yellow-1)',
  'gray-1': 'var(--gray-1)',
  'gray-2': 'var(--gray-2)',
  'gray-3': 'var(--gray-3)',
  'gray-4': 'var(--gray-4)',
}

module.exports = {
  theme: {
    colors: {
      primary: 'var(--primary)',
      secondary: 'var(--secondary)',
      surface: 'var(--surface)',
      disabled: 'var(--disabled)',
      background: 'var(--background)',
      'hover-overlay': 'var(--hover-overlay)',
      ...commonColors,
    },
    textColor: {
      'on-primary': 'var(--on-primary)',
      'on-surface': 'var(--on-surface)',
      primary: 'var(--text-primary)',
      secondary: 'var(--text-secondary)',
      disabled: 'var(--text-disabled)',
      hint: 'var(--text-hint)',
      icon: 'var(--text-icon)',
      tooltip: 'var(--text-tooltip)',
      'action-primary': 'var(--primary)',
      'action-secondary': 'var(--secondary)',
      ...commonColors,
    },
    opacity: {
      '0': '0',
      '08': '.08',
      '12': '.12',
      '25': '.25',
      '50': '.5',
      '75': '.75',
      '100': '1',
    },
    zIndex: {
      '-10': '-10',
      '-1': '-1',
      '0': '0',
      '10': '10',
      '20': '20',
      '30': '30',
      '40': '40',
      '50': '50',
      auto: 'auto',
    },
  },
  variants: {
    display: ['responsive', 'group-hover', 'group-focus'],
    opacity: [
      'responsive',
      'hover',
      'focus',
      'active',
      'group-hover',
      'group-focus',
    ],
  },
  plugins: [],
}
