const commonColors = {
  'green-1': 'var(--green-1)',
  'red-1': 'var(--red-1)',
  'violet-1': 'var(--violet-1)',
  'violet-2': 'var(--violet-2)',
  'yellow-1': 'var(--yellow-1)',
  'gray-1': 'var(--gray-1)',
  'gray-2': 'var(--gray-2)',
  'gray-3': 'var(--gray-3)',
  'gray-4': 'var(--gray-4)',
}

module.exports = {
  theme: {
    colors: {
      primary: 'var(--primary)',
      'background-primary': 'var(--primary-background)',
      secondary: 'var(--secondary)',
      surface: 'var(--surface)',
      disabled: 'var(--disabled)',
      background: 'var(--background)',
      'hover-overlay': 'var(--hover-overlay)',
      divider: 'var(--divider)',
      input: 'var(--input-background)',
      editor: 'var(--editor-background)',
      ...commonColors,
    },
    textColor: {
      'on-primary': 'var(--on-primary)',
      'on-surface': 'var(--on-surface)',
      primary: 'var(--text-primary)',
      secondary: 'var(--text-secondary)',
      disabled: 'var(--text-disabled)',
      hint: 'var(--text-hint)',
      icon: 'var(--text-icon)',
      'action-primary': 'var(--primary)',
      'action-secondary': 'var(--secondary)',
      ...commonColors,
    },
    opacity: {
      0: '0',
      '08': '.08',
      12: '.12',
      25: '.25',
      50: '.5',
      75: '.75',
      100: '1',
    },
    zIndex: {
      '-10': '-10',
      '-1': '-1',
      0: '0',
      1: '1',
      10: '10',
      20: '20',
      30: '30',
      40: '40',
      50: '50',
      auto: 'auto',
    },
    borderRadius: {
      none: '0',
      sm: '0.125rem',
      default: '0.25rem',
      md: '0.375rem',
      lg: '0.5rem',
      xl: '0.75rem',
      full: '9999px',
    },
    boxShadow: {
      xs: '0 0 0 1px rgba(0, 0, 0, 0.05)',
      sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
      default: '0 2px 8px 0 rgba(0, 0, 0, 0.12)',
      md:
        '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
      lg:
        '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
      xl:
        '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
      '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
      inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
      outline: '0 0 0 3px rgba(66, 153, 225, 0.5)',
      none: 'none',
    },
    maxWidth: {
      xxs: '12rem',
      xs: '20rem',
      sm: '24rem',
      md: '28rem',
      lg: '32rem',
      xl: '36rem',
      '2xl': '42rem',
      '3xl': '48rem',
      '4xl': '56rem',
      '5xl': '64rem',
      '6xl': '72rem',
      full: '100%',
      'screen-sm': '640px',
      'screen-md': '768px',
      'screen-lg': '1024px',
      'screen-xl': '1280px',
    },
  },
  variants: {
    display: ['responsive', 'group-hover', 'group-focus'],
    opacity: [
      'responsive',
      'hover',
      'focus',
      'active',
      'group-hover',
      'group-focus',
    ],
  },
  future: {
    removeDeprecatedGapUtilities: true,
    purgeLayersByDefault: true,
  },
  plugins: [],
}
