module.exports = {
  collectCoverageFrom: ['src/**/*.{ts,tsx}'],
  setupFiles: ['react-app-polyfill/jsdom', './src/setupTests.ts'],
  setupFilesAfterEnv: ['./src/setupTestsAfterEnv.ts'],
  testMatch: [
    '<rootDir>/src/**/__tests__/**/*.{ts,tsx}',
    '<rootDir>/src/**/?(*.)(spec|test).{ts,tsx}',
  ],
  testEnvironment: 'jsdom',
  testURL: 'http://localhost',
  transform: {
    '^.+\\.(ts|tsx)$': 'babel-jest',
    '^.+\\.(gql|graphql)$': 'jest-transform-graphql',
    '^.+\\.css$': '<rootDir>/jest/cssTransform.js',
    '^(?!.*\\.(js|jsx|css|json)$)': '<rootDir>/jest/fileTransform.js',
  },
  transformIgnorePatterns: [
    '[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$',
    '^.+\\.module\\.(css|sass|scss)$',
  ],
  moduleNameMapper: {
    '^react-native$': 'react-native-web',
    '^.+\\.global\\.(css|sass|scss)$': 'identity-obj-proxy',
    '^hooks/(.*)': '<rootDir>/src/hooks/$1',
    '^assets/(.*)': '<rootDir>/src/assets/$1',
    '^notification/(.*)': '<rootDir>/src/notification/$1',
    '^utils/(.*)': '<rootDir>/src/utils/$1',
    '^components/(.*)': '<rootDir>/src/components/$1',
    '^views/(.*)': '<rootDir>/src/components/views/$1',
    '^forms/(.*)': '<rootDir>/src/components/forms/$1',
    '^pages/(.*)': '<rootDir>/src/components/pages/$1',
    '^routes/(.*)': '<rootDir>/src/components/routes/$1',
    '^resolvers/(.*)': '<rootDir>/src/resolvers/$1',
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'json', 'jsx', 'node'],
}
