module.exports = {
  theme: {
    colors: {
      primary: 'var(--color-primary)',
      secondary: 'var(--color-secondary)',
      success: 'var(--color-success)',
      error: 'var(--color-error)',
      emphasis: 'var(--color-emphasis)',
      surface: 'var(--color-surface)',
      outline: 'var(--color-outline)',
      muted: 'var(--color-muted)',
      disabled: 'var(--color-disabled)',
    },
    textColor: {
      'on-primary': 'var(--color-on-primary)',
      'on-secondary': 'var(--color-on-secondary)',
      'on-surface': 'var(--color-on-surface)',
      'on-success': 'var(--color-on-success)',
      'on-error': 'var(--color-on-error)',
      'on-emphasis': 'var(--color-on-emphasis)',
      primary: 'var(--color-text-primary)',
      secondary: 'var(--color-text-secondary)',
      disabled: 'var(--color-text-disabled)',
      hint: 'var(--color-text-hint)',
      icon: 'var(--color-text-icon)',
      'action-primary': 'var(--color-primary)',
      'action-secondary': 'var(--color-secondary)',
      error: 'var(--color-error)',
      emphasis: 'var(--color-emphasis)',
      success: 'var(--color-success)',
      outline: 'var(--color-outline)',
      muted: 'var(--color-muted)',
    },
  },
  variants: {},
  plugins: [],
}
