const commonColors = {
  success: 'var(--color-success)',
  error: 'var(--color-error)',
  emphasis: 'var(--color-emphasis)',
  outline: 'var(--color-outline)',
  muted: 'var(--color-muted)',
  'muted-2': 'var(--color-muted-2)',
}

module.exports = {
  theme: {
    colors: {
      primary: 'var(--color-primary)',
      secondary: 'var(--color-secondary)',
      surface: 'var(--color-surface)',
      disabled: 'var(--color-disabled)',
      ...commonColors,
    },
    textColor: {
      'on-primary': 'var(--color-on-primary)',
      'on-secondary': 'var(--color-on-secondary)',
      'on-surface': 'var(--color-on-surface)',
      'on-success': 'var(--color-on-success)',
      'on-error': 'var(--color-on-error)',
      'on-emphasis': 'var(--color-on-emphasis)',
      primary: 'var(--color-text-primary)',
      secondary: 'var(--color-text-secondary)',
      disabled: 'var(--color-text-disabled)',
      hint: 'var(--color-text-hint)',
      icon: 'var(--color-text-icon)',
      'action-primary': 'var(--color-primary)',
      'action-secondary': 'var(--color-secondary)',
      ...commonColors,
    },
    opacity: {
      '0': '0',
      '08': '.08',
      '12': '.12',
      '25': '.25',
      '50': '.5',
      '75': '.75',
      '100': '1',
    },
    zIndex: {
      '-10': '-10',
      '-1': '-1',
      '0': '0',
      '10': '10',
      '20': '20',
      '30': '30',
      '40': '40',
      '50': '50',
      auto: 'auto',
    },
  },
  variants: {},
  plugins: [],
}
