const STATIC_FOLDER = 'static'
const STATIC_RUNTIME_PATH = `${STATIC_FOLDER}/runtime`
const STATIC_CHUNKS_PATH = `${STATIC_FOLDER}/chunks`
const STATIC_MEDIA_PATH = `${STATIC_FOLDER}/media`

const STATIC_RUNTIME_MAIN = `${STATIC_RUNTIME_PATH}/main`
const STATIC_RUNTIME_WEBPACK = `${STATIC_RUNTIME_PATH}/webpack`

module.exports = {
  STATIC_FOLDER,
  STATIC_CHUNKS_PATH,
  STATIC_MEDIA_PATH,
  STATIC_RUNTIME_PATH,
  STATIC_RUNTIME_MAIN,
  STATIC_RUNTIME_WEBPACK,
}
