export enum ActionTypes {
  USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST',
  USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE',
  USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST',
  USER_LOGGED_IN = 'USER_LOGGED_IN',
  USER_LOGGED_OUT = 'USER_LOGGED_OUT',

  REGISTER_NEW_USER_REQUEST = 'REGISTER_NEW_USER_REQUEST',
  REGISTER_NEW_USER_SUCCESS = 'REGISTER_NEW_USER_SUCCESS',
  REGISTER_NEW_USER_FAILURE = 'REGISTER_NEW_USER_FAILURE',

  FETCH_CURRENT_USER_REQUEST = 'FETCH_CURRENT_USER_REQUEST',
  FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS',
  FETCH_CURRENT_USER_FAILURE = 'FETCH_CURRENT_USER_FAILURE',

  FETCH_DECKS_REQUEST = 'FETCH_DECKS_REQUEST',
  FETCH_DECKS_SUCCESS = 'FETCH_DECKS_SUCCESS',
  FETCH_DECKS_FAILURE = 'FETCH_DECKS_FAILURE',
}

export interface UserCredentials {
  username: string
  accessKey: string
  authentication: string
}

export interface DeckEntity {
  deckId: number
  title: string
  description?: string
}
