mutation addModel($name: String!, $fields: [FieldInput], $templates: [TemplateInput]) {
  createModel(name: $name, fields: $fields, templates: $templates) {
    id
    name
    templates {
      id
      name
    }
  }
}
