query getModel($id: ID!) {
  cardModel(id: $id) {
    id
    name
    fields {
      id
      name
    }
    templates {
      id
      name
      frontSide {
        ...DraftContent
      }
      backSide {
        ...DraftContent
      }
    }
    notes {
      id
    }
  }
}

fragment DraftContent on ContentState {
  id
  blocks {
    key
    type
    text
    depth
    inlineStyleRanges {
      style
      offset
      length
    }
    entityRanges {
      key
      length
      offset
    }
    data
  }
  entityMap
}
