name: CI
on:
  pull_request:
    types:
    - opened
    - synchronize
  push:
    branches:
    - main
    - canary

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: NodeJS 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install --frozen-lockfile --check-files
    - uses: actions/cache@v2
      id: cache-build
      with:
        path: ./*
        key: ${{ github.sha }}

  messages:
    runs-on: ubuntu-latest
    needs: install

    steps:
    - name: Restore cache
      uses: actions/cache@v2
      id: restore-build
      with:
        path: ./*
        key: ${{ github.sha }}
    - name: Check messages
      run: |
        yarn extract
        yarn compile --strict

  lint:
    runs-on: ubuntu-latest
    needs: install

    steps:
    - name: Restore cache
      uses: actions/cache@v2
      id: restore-build
      with:
        path: ./*
        key: ${{ github.sha }}
    - name: NodeJS 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Messages compilation
      run: yarn compile
    - name: Lint
      run: |
        yarn lint
        # TODO: Temporarily disabled
        # yarn lint:ts
        yarn lint:css

  storybook:
    runs-on: ubuntu-latest
    needs: install
    steps:
    - name: Restore cache
      uses: actions/cache@v2
      id: restore-build
      with:
        path: ./*
        key: ${{ github.sha }}
    - name: NodeJS 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Storybook Smoke Test
      run: |
        yarn prebuild
        yarn storybook --smoke-test --ci --quiet

  test:
    runs-on: ubuntu-latest
    needs: install

    steps:
    - name: Restore cache
      uses: actions/cache@v2
      id: restore-build
      with:
        path: ./*
        key: ${{ github.sha }}
    - name: NodeJS 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Test App
      run: |
        yarn compile
        yarn test

  build:
    runs-on: ubuntu-latest
    needs: install

    steps:
    - name: Restore cache
      uses: actions/cache@v2
      id: restore-build
      with:
        path: ./*
        key: ${{ github.sha }}
    - name: NodeJS 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Build
      run: yarn build
    - uses: actions/upload-artifact@v2
      if: github.ref == 'refs/heads/main'
      with:
        name: build-artifact
        path: ./build
