name: CI
on:
  pull_request:
    types:
    - opened
    - synchronize
  push:
    branches:
    - main
    - canary

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: NodeJS 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm install --legacy-peer-deps
    - uses: actions/cache@v2
      id: cache-build
      with:
        path: ./*
        key: ${{ github.sha }}

  messages:
    runs-on: ubuntu-latest
    needs: install

    steps:
    - name: Restore cache
      uses: actions/cache@v2
      id: restore-build
      with:
        path: ./*
        key: ${{ github.sha }}
    - name: Check messages
      run: |
        npm run extract
        npm run compile --strict

  lint:
    runs-on: ubuntu-latest
    needs: install

    steps:
    - name: Restore cache
      uses: actions/cache@v2
      id: restore-build
      with:
        path: ./*
        key: ${{ github.sha }}
    - name: NodeJS 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Messages compilation
      run: npm run compile
    - name: Lint
      run: |
        npm run lint
        npm run lint:ts
        npm run lint:css

  test:
    runs-on: ubuntu-latest
    needs: install

    steps:
    - name: Restore cache
      uses: actions/cache@v2
      id: restore-build
      with:
        path: ./*
        key: ${{ github.sha }}
    - name: NodeJS 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Test App
      run: |
        npm run compile
        npm run test

  build:
    runs-on: ubuntu-latest
    needs: install

    steps:
    - name: Restore cache
      uses: actions/cache@v2
      id: restore-build
      with:
        path: ./*
        key: ${{ github.sha }}
    - name: NodeJS 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Build
      run: npm run build
    - uses: actions/upload-artifact@v2
      if: github.ref == 'refs/heads/main'
      with:
        name: build-artifact
        path: ./build
