name: CI
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: NodeJS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: |
        yarn
        yarn --cwd api
        yarn --cwd app
    - name: Messages compilation
      run: yarn --cwd app compile
    - name: Lint
      run: yarn lint
      env:
        CI: true
    - name: Lint CSS
      run: yarn lint-css
      env:
        CI: true

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: |
          yarn
          yarn --cwd api
          yarn --cwd app
      - name: Test App
        run: |
          yarn --cwd app compile
          yarn --cwd app test
      - name: Test API
          yarn --cwd api test
        env:
          CI: true

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: NodeJS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: |
        yarn --cwd api
        yarn --cwd app
    - name: Build
      run: |
        yarn --cwd api build
        yarn --cwd app build
      env:
        CI: true
