name: CI
on:
  pull_request:
    types:
    - opened
    - synchronize
  push:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: NodeJS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: yarn
    - name: Messages compilation
      run: yarn compile
    - name: Lint
      run: |
        yarn lint
        yarn lint:ts
        yarn lint:css
      env:
        CI: true

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn
      - name: Test App
        run: |
          yarn compile
          yarn test
        env:
          CI: true

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: NodeJS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn build
      env:
        CI: true

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]

    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_REGISTRY_SERVER }}
        username: ${{ secrets.ACR_REGISTRY_USERNAME }}
        password: ${{ secrets.ACR_REGISTRY_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}
    - name: Deploy image
      env:
        REGISTRY_SERVER: ${{ secrets.ACR_REGISTRY_SERVER }}
        VERSION: ${{ steps.get_version.outputs.VERSION }}
        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      run: ./deploy.sh
