name: CI
on:
  pull_request:
    branches:
    - master

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: NodeJS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: yarn
    - name: Lint
      run: |
        yarn workspace @cramkle/app compile
        yarn workspaces run lint
      env:
        CI: true
    - name: Lint CSS
      run: yarn workspace @cramkle/app lint-css
      env:
        CI: true

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: NodeJS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: yarn
    - name: Build
      run: yarn workspaces run build
      env:
        CI: true
