name: Node CI
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: NodeJS 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: yarn install, build, and test
      run: |
        yarn install --frozen-lockfile
        yarn build
        yarn test
    - name: Danger
      run: yarn danger ci
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
